

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: minha_base
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - postgres
