
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  jupyter:
    build: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ../data:/home/jovyan/data
    environment:
      - PYSPARK_SUBMIT_ARGS=--jars /opt/spark/jars/postgresql-42.7.3.jar pyspark-shell
    depends_on:
      - postgres
